import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNavbar from "./Component/Navbar/MainNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body className="min-h-screen"><div className="flex min-h-screen">
        <MainNavbar/> 
        <main className="min-w-0 flex-1 overflow-x-hidden bg-[#37353E]">{children}</main>
      </div></body>
    </html>
  );
}
